# SQL JOINS
# when data source is more than one table 

# Script for Customer Table

USE FLIPKART_DB;

DROP TABLE CUSTOMER_TB;

CREATE TABLE CUSTOMER_TB (
ID INT,
NAME VARCHAR(20),
AGE TINYINT,
ADDRESS VARCHAR(50),
WALLET_BAL FLOAT);

INSERT INTO CUSTOMER_TB VALUES (1, 'RAMESH', 32,'AHMEDABAD',200);
INSERT INTO CUSTOMER_TB VALUES (2, 'KHILAN', 23,'DELHI',7500);
INSERT INTO CUSTOMER_TB VALUES (3, 'KAUSHIK', 25,'KOTA',12000);
INSERT INTO CUSTOMER_TB VALUES (4, 'CHAITALI', 22,'MUMBAI',6500);
INSERT INTO CUSTOMER_TB VALUES (5, 'HARDIK', 27,'BHOPAL',6500);
INSERT INTO CUSTOMER_TB VALUES (6, 'KOMAL', 26,'MANIPUR',750);
INSERT INTO CUSTOMER_TB VALUES (7, 'DUFFY', 27,'INDORE',500);

# SCRIPT FOR ORDER TABLE

CREATE TABLE ORDER_TB(
OID INT,
DATE DATE,
C_ID INT,
AMOUNT FLOAT);

INSERT INTO ORDER_TB VALUES (102, '2009-10-08','3',3000);
INSERT INTO ORDER_TB VALUES (100, '2009-10-08','3',1500);
INSERT INTO ORDER_TB VALUES (101, '2009-11-20','2',1560);
INSERT INTO ORDER_TB VALUES (103, '2008-05-20','4',2060);
INSERT INTO ORDER_TB VALUES (199, '2020-05-20',null,9999);

SELECT * FROM CUSTOMER_TB;
SELECT * FROM ORDER_TB;
DROP TABLE ORDER_TB;

SELECT distinct C_ID FROM ORDER_TB WHERE C_ID IS NOT NULL;

SELECT * FROM CUSTOMER_TB WHERE ID IN(2,3,4);       # WHO HAS PURCHASED
SELECT * FROM CUSTOMER_TB WHERE ID NOT IN(2,3,4);   # WHO HAS NOT PURCHASED

SELECT * FROM CUSTOMER_TB WHERE ID IN(SELECT distinct C_ID FROM ORDER_TB); 
SELECT * FROM CUSTOMER_TB WHERE ID NOT IN(SELECT distinct C_ID FROM ORDER_TB WHERE C_ID IS NOT NULL);

#OPTIMISED SOLUTION

# JOINS

# COMMAND IS USED TO COMBINE COLUMNS FROM TWO OR MORE TABLES
#IN REAL WORLD NOT ALL DATA WILL BE PRESENT IN SINGLE TABLE (USED FOR REPORTING PURPOSE)

#INNER JOIN
#LEFT JOIN
#RIGHT JOIN
#FULL JOIN
#SELF JOIN
#CROSS JOIN (CARETESIAN JOIN)

#INNER JOIN
#RECORDS SHOULD MATCH ON BOTH TABLE
# By using inner join we will get only the matching records from both table

SELECT * FROM CUSTOMER_TB;
SELECT * FROM ORDER_TB;

SELECT A.NAME, A.ADDRESS, B.OID, B.DATE 
FROM CUSTOMER_TB A INNER JOIN ORDER_TB B
ON A.ID = B.C_ID; # (A,B ARE THE ALIAS NAME) THIS IS THE OPTIMIED CODE . SHOULD BE CONSIDER FOR WORK

SELECT CUSTOMER_TB.NAME, CUSTOMER_TB.ADDRESS, ORDER_TB.OID, ORDER_TB.DATE
FROM CUSTOMER_TB INNER JOIN ORDER_TB
ON CUSTOMER_TB.ID = ORDER_TB.C_ID; # THIS IS WITHOUT ALIAS NAME

# MAKE SURE TO USE ALIAS TO AVOID LONG CODING

SELECT NAME, ADDRESS, OID, DATE
FROM CUSTOMER_TB INNER JOIN ORDER_TB
ON ID=C_ID;                                  # THIS WILL ALSO WORK . ONLY WHEN COLUMN NAMES IN BOTH TABLES ARE DIFFERENT. OTHERWISE IT WILL CREATE CONFUSION
# ABOVE IS NOT THE OPTIMISED SOLUTION MAKE THE HABBIT TO USE ALIAS WITHOUT FAIL.

#LEFT JOIN
# LEFT TABLE       # RIGHT TABLE
#DISPLAY ALL RECORDS FROM LEFT TABLE

SELECT A.NAME, A.ADDRESS, B.OID, B.DATE 
FROM CUSTOMER_TB A LEFT JOIN ORDER_TB B
ON A.ID = B.C_ID; # (A,B ARE THE ALIAS NAME) THIS IS THE OPTIMIED CODE . SHOULD BE CONSIDER FOR WORK

#RIGHT JOIN
# LEFT TABLE       # RIGHT TABLE
#DISPLAY ALL RECORDS FROM RIGHT TABLE

SELECT A.NAME, A.ADDRESS, B.OID, B.DATE 
FROM CUSTOMER_TB A RIGHT JOIN ORDER_TB B
ON A.ID = B.C_ID; # (A,B ARE THE ALIAS NAME) THIS IS THE OPTIMIED CODE . SHOULD BE CONSIDER FOR WORK

# PROBLEMS/ QUESTIONS SOLVED BY USING JOINS:

# 1. How many customers are there in amazon ?
# Here no need of join. we can directly refer customer table. but this can also be solved using join

SELECT COUNT(DISTINCT A.NAME) UNIQUE_NAMES_COUNT
FROM CUSTOMER_TB A LEFT JOIN ORDER_TB B
ON A.ID = B.C_ID; # CORRECT ANSWER IS 7

# 2. How many customers didnt do shopping/ didnt buy anything ?
SELECT COUNT(DISTINCT A.NAME) CUSTOMER_COUNT 
FROM CUSTOMER_TB A LEFT JOIN ORDER_TB B
ON A.ID = B.C_ID 
WHERE B.OID IS NULL;   # CORRECT ANSWER IS 4

# WHILE USING WHERE CONDITION , IF U WANT TO GIVE NOT EQUAL TO THEN USE != OR <> , THIS WILL NOT BE APPLICABLE FOR NULL
# IF INCASE U WANT TO USE ON NULL, GIVE:  IS NULL   OR    IS NOT NULL

# 3. How many registered customers, has purchase history amazon customer table ?
SELECT COUNT(DISTINCT A.NAME) CUSTOMER_COUNT
FROM CUSTOMER_TB A LEFT JOIN ORDER_TB B
ON A.ID = B.C_ID
WHERE B.OID IS NOT NULL;

# 4. How many orders placed as guest ?
SELECT COUNT(B.OID) CUSTOMER_COUNT
FROM CUSTOMER_TB A RIGHT JOIN ORDER_TB B
ON A.ID = B.C_ID
WHERE A.NAME IS NULL;




























