SELECT * FROM flipkart_db.student_info;
ALTER TABLE flipkart_db.student_info rename column ï»¿ID to ID ;

SELECT * FROM student_info;

SELECT *, MARKS/10 DECI_MARKS FROM student_info;
select * from student_info;


# WINDOW FUNCTIONS / ANALYTICAL FUNCTION --------> rank, dense rank, row number, lead lag
#AVG()
#RANK()
#DENSE_RANK()
#ROW_NUMBER()
#LEAD()
#LAG()
# while writing windown function over is mandatory

SELECT ID, NAME, MARKS, rank() over(order by MARKS)"RANK" FROM student_info;                             # RANKING BASED ON ASCENDING MARKS  (LOWEST TO HIGHEST)
SELECT ID, NAME, MARKS, rank() over(order by MARKS desc) RANK_OF_STUDENTS FROM student_info;             # RANKING BASED ON DESCENDING MARKS (HIGHESHT TO LOWEST)

#TO APPLY FILTER CONDITION:
SELECT * FROM(
SELECT ID, NAME, MARKS, rank() over(order by MARKS desc) RANK_OF_STUDENTS FROM student_info ) A
WHERE RANK_OF_STUDENTS =5;                                                                         #USING SUB QUERY, AS WE CANNOT APPLY WHERE COND ON DERIVED COLS

# PROBLEM IN RANK FUNTION IS WHILE ALLOTING RANK, NUMBER IS SKIPPED IF TWO OR MORE RECORDS ARE OF SAME RANK
# TO SOLVE THE PROBLEM USE DENSE_RANK() FUNCTION ....RANKS ARE CONSECUTIVE NUMBERS

SELECT ID, NAME, MARKS, DENSE_RANK() OVER(ORDER BY MARKS DESC) 'rank' FROM student_info;

#PROBLEMS: EACH AND EVERY STUDENT/ RECORD MUST GET UNIQUE RANK,,,WHICH CAN ALSO ACT AS PRIMARY KEY

SELECT ID, NAME, MARKS, ROW_NUMBER() OVER(ORDER BY MARKS DESC) 'RANK' FROM student_info;
SELECT ID, NAME, MARKS, ROW_NUMBER() OVER(ORDER BY MARKS DESC, NAME ASC) 'RANK' FROM student_info;  # SORT BASED ON MARKS FOLLOWED BY ALPHABETICAL ORDER
SELECT ID, NAME, MARKS, ROW_NUMBER() OVER(ORDER BY MARKS DESC, NAME DESC) 'RANK' FROM student_info; # SORT BASED ON MARKS FOLLOWED BY ALPHABETICAL ORDER

# ANOTHER PROBLEM :

SELECT * FROM student_info1;

# WE NEED TO GIVE RANKING TO STUDENTS SUBJECT WISE FROM HIGHEST TO LOWEST                   
SELECT * FROM(
SELECT ID, NAME , MEDIUM, MARKS , DENSE_RANK() OVER(ORDER BY MEDIUM, MARKS DESC)"RANK" FROM STUDENT_INFO1) A
WHERE MEDIUM = "ENGLISH"
UNION
SELECT * FROM (
SELECT ID, NAME,MEDIUM,MARKS, DENSE_RANK() OVER(ORDER BY MEDIUM DESC, MARKS DESC)'RANK' FROM student_info1) A
WHERE MEDIUM = 'KANNADA';

# OPTIMISED SOLUTION

SELECT ID, NAME,MEDIUM, MARKS, DENSE_RANK() OVER(PARTITION BY MEDIUM ORDER BY MARKS DESC) "DENSE_RANK" FROM student_info1;

# TO GET 3RD HIGHEST / STUDENT WITH 3RD MAXIMUM MARKS

SELECT * FROM(
SELECT ID, NAME,MEDIUM, MARKS, DENSE_RANK() OVER(PARTITION BY MEDIUM ORDER BY MARKS DESC) "DENSSE_RANK" FROM student_info1) A
WHERE DENSSE_RANK = 3;

DROP TABLE IF EXISTS student_score;

CREATE TABLE student_score (
  student_id SERIAL PRIMARY KEY,
  student_name VARCHAR(30),
  dep_name VARCHAR(40),
  score INT
);

INSERT INTO student_score VALUES (11, 'Ibrahim', 'Computer Science', 80);
INSERT INTO student_score VALUES (7, 'Taiwo', 'Microbiology', 76);
INSERT INTO student_score VALUES (9, 'Nurain', 'Biochemistry', 80);
INSERT INTO student_score VALUES (8, 'Joel', 'Computer Science', 90);
INSERT INTO student_score VALUES (10, 'Mustapha', 'Industrial Chemistry', 78);
INSERT INTO student_score VALUES (5, 'Muritadoh', 'Biochemistry', 85);
INSERT INTO student_score VALUES (2, 'Yusuf', 'Biochemistry', 70);
INSERT INTO student_score VALUES (3, 'Habeebah', 'Microbiology', 80);
INSERT INTO student_score VALUES (1, 'Tomiwa', 'Microbiology', 65);
INSERT INTO student_score VALUES (4, 'Gbadebo', 'Computer Science', 80);
INSERT INTO student_score VALUES (12, 'Tolu', 'Computer Science', 67);

#TO GET COLUMNS WITH MAXIMUM MARKS DEPT WISE, MIN MARKS DEPT WISE AND AVG MARKS DEPT WISE

SELECT * FROM student_score;

SELECT STUDENT_ID,STUDENT_NAME, DEP_NAME, SCORE ,
MAX(SCORE) OVER(PARTITION BY DEP_NAME) DEPARTMENT_MAX_MARKS,
MIN(SCORE) OVER(PARTITION BY DEP_NAME) DEPARTMENT_MIN_MARKS,
ROUND(AVG(SCORE) OVER(PARTITION BY DEP_NAME),2) DEPARTMENT_AVG_MARKS
FROM student_score;

# GIVE DEPARTMENT WISE RANKS

SELECT * ,
RANK() OVER(PARTITION BY DEP_NAME ORDER BY SCORE DESC) RANK_OF_STUDENT
FROM student_score;

SELECT *, DENSE_RANK() OVER (PARTITION BY DEP_NAME ORDER BY SCORE DESC) DENSE_RANK_OF_STUDENT
FROM student_score;

WITH CTE AS (SELECT *, ROW_NUMBER() OVER(PARTITION BY DEP_NAME ORDER BY SCORE DESC, STUDENT_NAME ASC) UNIQUE_RANK FROM STUDENT_SCORE)
SELECT * FROM CTE WHERE UNIQUE_RANK =2;

SELECT * FROM (SELECT *, ROW_NUMBER() OVER(PARTITION BY DEP_NAME ORDER BY SCORE DESC, STUDENT_NAME ASC) UNIQUE_RANK FROM STUDENT_SCORE) ALIAS
WHERE UNIQUE_RANK=3;

#############################################################
use flipkart_db;
DROP TABLE IF EXISTS WINDOWS_FUNS_EXP;
CREATE TABLE WINDOWS_FUNS_EXP(
S_YEAR INT,
T_SALES INT );

INSERT INTO WINDOWS_FUNS_EXP(S_YEAR,T_SALES) VALUES
(2015, 23000),(2016,25000),(2017,34000),(2018,32000), (2019,33000);

select * from windows_funs_exp;

# calculate YearOnYear Sales (YOY) :

with cte as (SELECT S_YEAR, T_SALES, LAG(T_SALES) OVER (ORDER BY S_YEAR) P_SALES FROM windows_funs_exp)
			select s_year, t_sales, ((t_sales-p_sales)/p_sales)*100 YOY from cte;

DROP TABLE IF EXISTS WINDOWS_FUNS_EXP1;
CREATE TABLE WINDOWS_FUNS_EXP1(
S_YEAR INT,
S_PRODUCT VARCHAR(20),
T_SALES INT );


INSERT INTO WINDOWS_FUNS_EXP1(S_YEAR,S_PRODUCT,T_SALES) VALUES
(2015,'IPHONE', 23000),(2016,'IPHONE',25000),(2017,'IPHONE',34000),(2018,'IPHONE',32000), (2019,'IPHONE',33000),
(2015,'SAMSUNG',21000),(2016,'SAMSUNG',20000),(2017,'SAMSUNG',31500),(2018,'SAMSUNG',29750), (2019,'SAMSUNG',24500)
;
 
select * from windows_funs_exp1;

WITH CTE AS(select S_YEAR, S_PRODUCT,T_SALES, LAG(T_SALES)OVER( PARTITION BY S_PRODUCT ORDER BY S_YEAR)P_SALES FROM windows_funs_exp1)
		SELECT S_YEAR, S_PRODUCT, ((T_SALES - P_SALES)/ P_SALES)*100 YOY FROM CTE;


